services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: runplanprod
      POSTGRES_USER: runplan_user
      POSTGRES_PASSWORD: runplan_secure_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    networks:
      - gpx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U runplan_user -d runplanprod"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://runplan_user:runplan_secure_password_123@database:5432/runplanprod
      - JWT_SECRET_KEY=your-super-secure-jwt-secret-key-change-in-production
    networks:
      - gpx-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gpx-network
    environment:
      - NODE_ENV=production

networks:
  gpx-network:
    driver: bridge

volumes:
  gpx-data:
  postgres_data: