services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

    networks:
      - gpx-network


networks:
  gpx-network:
    driver: bridge

volumes:
  gpx-data: